
import React, { useState } from 'react';
import { useStore } from '../../context/StoreContext';
import { useToast } from '../../context/ToastContext';
import { Student, StudentStatus } from '../../types';
import { exportToCSV } from '../../utils/csvExport';
import { useNavigate } from 'react-router-dom';
import ConfirmationModal from '../../components/ConfirmationModal';

const StudentsList: React.FC = () => {
  const { students, updateStudent, deleteStudent, addStudent, academySettings, markAttendance, promoteStudent, libraryResources } = useStore();
  const { addToast } = useToast();
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');
  const [showModal, setShowModal] = useState(false);
  const [editingStudent, setEditingStudent] = useState<Student | null>(null);
  
  // Confirmation Modal
  const [confirmModal, setConfirmModal] = useState<{isOpen: boolean, title: string, message: string, action: () => void, type?: 'danger'|'info'}>({
      isOpen: false, title: '', message: '', action: () => {}
  });
  
  // Dossier View State
  const [selectedStudentId, setSelectedStudentId] = useState<string | null>(null);
  const selectedStudent = students.find(s => s.id === selectedStudentId);

  // Form State
  const initialFormState = {
      name: '', email: '', rank: 'White Belt', status: 'active' as StudentStatus, program: 'Adults', balance: 0, avatarUrl: ''
  };
  const [formData, setFormData] = useState(initialFormState);

  const filteredStudents = students.filter(student => {
    const matchesSearch = student.name.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          student.email.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = filterStatus === 'all' || student.status === filterStatus;
    return matchesSearch && matchesStatus;
  });

  const handleExport = () => {
      const dataToExport = filteredStudents.map(({ classesId, promotionHistory, ...rest }) => rest);
      exportToCSV(dataToExport, 'Listado_Alumnos');
      addToast('Archivo CSV generado', 'success');
  };

  const getStatusColor = (status: string) => {
      switch(status) {
          case 'active': return 'bg-green-50 text-success ring-success/20'; 
          case 'debtor': return 'bg-yellow-50 text-warning ring-warning/20';
          case 'exam_ready': return 'bg-blue-50 text-info ring-info/20';
          default: return 'bg-gray-50 text-gray-500 ring-gray-200';
      }
  };

  const getStatusLabel = (status: string) => {
      switch(status) {
          case 'active': return 'AL DÍA';
          case 'debtor': return 'DEUDOR';
          case 'exam_ready': return 'EXAMEN LISTO';
          default: return 'INACTIVO';
      }
  };

  const handleDelete = (id: string, e?: React.MouseEvent) => {
      e?.stopPropagation();
      setConfirmModal({
          isOpen: true,
          title: 'Eliminar Alumno',
          message: '¿Estás seguro? Esta acción es irreversible y eliminará el historial del alumno.',
          type: 'danger',
          action: () => {
              deleteStudent(id);
              if (selectedStudentId === id) setSelectedStudentId(null);
              addToast('Alumno eliminado correctamente', 'success');
              setConfirmModal(prev => ({...prev, isOpen: false}));
          }
      });
  };

  const handleEdit = (student: Student, e?: React.MouseEvent) => {
      e?.stopPropagation();
      setEditingStudent(student);
      setFormData({
          name: student.name,
          email: student.email,
          rank: student.rank,
          status: student.status,
          program: student.program,
          balance: student.balance,
          avatarUrl: student.avatarUrl || ''
      });
      setShowModal(true);
  };

  const handleCreate = () => {
      setEditingStudent(null);
      setFormData({ ...initialFormState, avatarUrl: `https://i.pravatar.cc/150?u=${Date.now()}` });
      setShowModal(true);
  };

  const handleSubmit = (e: React.FormEvent) => {
      e.preventDefault();
      if (editingStudent) {
          updateStudent({
              ...editingStudent,
              ...formData
          });
          addToast('Alumno actualizado', 'success');
      } else {
          const selectedRank = academySettings.ranks.find(r => r.name === formData.rank);
          addStudent({
              id: '', // Will be generated by StoreContext
              userId: '', // Will be generated
              academyId: '', // Will be injected by StoreContext
              ...formData,
              rankId: selectedRank?.id || 'rank-1',
              rankColor: selectedRank?.color || 'white',
              stripes: 0,
              attendance: 0,
              totalAttendance: 0,
              joinDate: new Date().toLocaleDateString(),
              classesId: [],
              attendanceHistory: []
          });
          addToast('Alumno creado exitosamente', 'success');
          // Optional: Alert user about auto-creation via toast detail or modal
          setTimeout(() => alert(`Credenciales generadas:\nEmail: ${formData.email}\nPass: Pulse123!`), 500);
      }
      setShowModal(false);
  };

  const handlePromote = () => {
      if (!selectedStudent) return;
      setConfirmModal({
          isOpen: true,
          title: 'Promover de Rango',
          message: `¿Estás seguro de promover a ${selectedStudent.name} al siguiente cinturón?`,
          type: 'info',
          action: () => {
              promoteStudent(selectedStudent.id);
              addToast(`${selectedStudent.name} ha sido promovido`, 'success');
              setConfirmModal(prev => ({...prev, isOpen: false}));
          }
      });
  };

  const handleSendMessage = () => {
      if (!selectedStudent) return;
      navigate('/master/communication', { state: { recipientId: selectedStudent.id } });
  };

  const completedVideos = selectedStudent 
    ? libraryResources.filter(r => r.completedBy.includes(selectedStudent.id)) 
    : [];

  // -------------------- DOSSIER VIEW --------------------
  if (selectedStudent) {
      const currentRankConfig = academySettings.ranks.find(r => r.id === selectedStudent.rankId);
      
      return (
          <div className="flex-1 overflow-y-auto p-4 md:p-8 lg:px-10 h-full animate-in fade-in slide-in-from-right-4 duration-300">
              <ConfirmationModal 
                isOpen={confirmModal.isOpen}
                title={confirmModal.title}
                message={confirmModal.message}
                onConfirm={confirmModal.action}
                onCancel={() => setConfirmModal(prev => ({...prev, isOpen: false}))}
                type={confirmModal.type}
              />

              <button onClick={() => setSelectedStudentId(null)} className="flex items-center gap-2 text-text-secondary hover:text-primary mb-6 transition-colors">
                  <span className="material-symbols-outlined">arrow_back</span>
                  <span>Volver a Lista</span>
              </button>

              <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
                  {/* Left Column: Profile Card */}
                  <div className="flex flex-col gap-6">
                      <div className="bg-white rounded-3xl p-8 border border-gray-100 shadow-card flex flex-col items-center text-center">
                          <img src={selectedStudent.avatarUrl} alt={selectedStudent.name} className="size-32 rounded-full object-cover border-4 border-gray-50 mb-4 shadow-sm" />
                          <h2 className="text-2xl font-bold text-text-main">{selectedStudent.name}</h2>
                          <p className="text-text-secondary mb-4">{selectedStudent.email}</p>
                          <span className={`inline-flex items-center rounded-full px-4 py-1.5 text-xs font-bold ring-1 ring-inset tracking-wide ${getStatusColor(selectedStudent.status)}`}>
                              {getStatusLabel(selectedStudent.status)}
                          </span>
                          
                          <div className="grid grid-cols-2 w-full gap-4 mt-8 pt-8 border-t border-gray-100">
                              <div className="flex flex-col">
                                  <span className="text-xs text-text-secondary font-bold uppercase tracking-wider">Programa</span>
                                  <span className="font-semibold text-text-main">{selectedStudent.program}</span>
                              </div>
                              <div className="flex flex-col">
                                  <span className="text-xs text-text-secondary font-bold uppercase tracking-wider">Se unió</span>
                                  <span className="font-semibold text-text-main">{selectedStudent.joinDate}</span>
                              </div>
                          </div>
                      </div>

                      {/* Quick Actions */}
                      <div className="bg-white rounded-3xl p-6 border border-gray-100 shadow-card">
                          <h3 className="font-bold text-lg text-text-main mb-4">Acciones Rápidas</h3>
                          <div className="flex flex-col gap-3">
                              <button 
                                onClick={() => { markAttendance(selectedStudent.id); addToast('Asistencia marcada', 'success'); }}
                                className="flex items-center gap-3 w-full p-3 rounded-xl hover:bg-gray-50 transition-colors text-left"
                              >
                                  <div className="size-10 rounded-full bg-green-50 text-green-600 flex items-center justify-center"><span className="material-symbols-outlined">check_circle</span></div>
                                  <span className="font-medium text-text-main">Marcar Asistencia Hoy</span>
                              </button>
                              <button 
                                onClick={handlePromote}
                                className="flex items-center gap-3 w-full p-3 rounded-xl hover:bg-gray-50 transition-colors text-left"
                              >
                                  <div className="size-10 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center"><span className="material-symbols-outlined">workspace_premium</span></div>
                                  <span className="font-medium text-text-main">Promover de Rango</span>
                              </button>
                              <button 
                                onClick={handleSendMessage}
                                className="flex items-center gap-3 w-full p-3 rounded-xl hover:bg-gray-50 transition-colors text-left"
                              >
                                  <div className="size-10 rounded-full bg-purple-50 text-purple-600 flex items-center justify-center"><span className="material-symbols-outlined">mail</span></div>
                                  <span className="font-medium text-text-main">Enviar Mensaje</span>
                              </button>
                              <button onClick={() => handleDelete(selectedStudent.id)} className="flex items-center gap-3 w-full p-3 rounded-xl hover:bg-red-50 transition-colors text-left group">
                                  <div className="size-10 rounded-full bg-red-50 text-red-500 group-hover:bg-red-100 flex items-center justify-center"><span className="material-symbols-outlined">delete</span></div>
                                  <span className="font-medium text-red-600">Eliminar Alumno</span>
                              </button>
                          </div>
                      </div>
                  </div>

                  {/* Right Column: Detailed Tabs */}
                  <div className="xl:col-span-2 flex flex-col gap-6">
                      {/* Attendance Stats */}
                      <div className="bg-white rounded-3xl p-8 border border-gray-100 shadow-card">
                          <div className="flex justify-between items-center mb-6">
                              <h3 className="font-bold text-lg text-text-main">Progreso de Cinturón</h3>
                              <div className="flex items-center gap-2">
                                  <div className="h-3 w-20 rounded shadow-sm" style={{ backgroundColor: selectedStudent.rankColor }}></div>
                                  <span className="font-bold text-sm">{selectedStudent.rank}</span>
                              </div>
                          </div>
                          
                          <div className="mb-2 flex justify-between text-sm font-medium">
                              <span className="text-text-secondary">Asistencia Actual</span>
                              <span className="text-text-main">{selectedStudent.attendance} / {currentRankConfig?.requiredAttendance || 100}</span>
                          </div>
                          <div className="w-full bg-gray-100 rounded-full h-3 mb-6">
                              <div className="bg-primary h-3 rounded-full transition-all duration-1000" style={{ width: `${Math.min((selectedStudent.attendance / (currentRankConfig?.requiredAttendance || 100)) * 100, 100)}%` }}></div>
                          </div>
                          
                          <div className="grid grid-cols-3 gap-4 text-center">
                              <div className="p-4 rounded-2xl bg-gray-50">
                                  <p className="text-2xl font-bold text-text-main">{selectedStudent.totalAttendance}</p>
                                  <p className="text-xs text-text-secondary font-bold uppercase">Total Clases</p>
                              </div>
                              <div className="p-4 rounded-2xl bg-gray-50">
                                  <p className="text-2xl font-bold text-text-main">{selectedStudent.stripes}</p>
                                  <p className="text-xs text-text-secondary font-bold uppercase">Grados (Stripes)</p>
                              </div>
                              <div className="p-4 rounded-2xl bg-gray-50">
                                  <p className="text-2xl font-bold text-text-main">{completedVideos.length}</p>
                                  <p className="text-xs text-text-secondary font-bold uppercase">Videos Estudiados</p>
                              </div>
                          </div>
                      </div>

                      {/* Timeline & Study History */}
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                          {/* Timeline */}
                          <div className="bg-white rounded-3xl p-8 border border-gray-100 shadow-card flex-1">
                              <h3 className="font-bold text-lg text-text-main mb-6">Línea de Tiempo</h3>
                              <div className="space-y-6">
                                  {/* Current Status */}
                                  <div className="flex gap-4">
                                      <div className="flex flex-col items-center gap-2">
                                          <div className="size-3 rounded-full bg-primary"></div>
                                          <div className="w-0.5 flex-1 bg-gray-200"></div>
                                      </div>
                                      <div className="pb-2">
                                          <p className="text-sm font-bold text-text-main">Estado Actual</p>
                                          <p className="text-sm text-text-secondary">Entrenando activamente en {selectedStudent.rank}</p>
                                      </div>
                                  </div>
                                  
                                  {/* Promotion History */}
                                  {selectedStudent.promotionHistory?.map((item, idx) => (
                                      <div key={idx} className="flex gap-4">
                                        <div className="flex flex-col items-center gap-2">
                                            <div className="size-3 rounded-full bg-gray-400"></div>
                                            {idx < (selectedStudent.promotionHistory?.length || 0) - 1 && <div className="w-0.5 flex-1 bg-gray-200"></div>}
                                        </div>
                                        <div className="pb-4">
                                            <p className="text-sm font-bold text-text-main">{item.rank}</p>
                                            <p className="text-xs text-text-secondary mb-1">{item.date}</p>
                                            {item.notes && <p className="text-sm text-text-secondary italic">"{item.notes}"</p>}
                                        </div>
                                      </div>
                                  ))}

                                  {(!selectedStudent.promotionHistory || selectedStudent.promotionHistory.length === 0) && (
                                       <div className="flex gap-4">
                                            <div className="flex flex-col items-center gap-2">
                                                <div className="size-3 rounded-full bg-gray-300"></div>
                                            </div>
                                            <div>
                                                <p className="text-sm font-bold text-text-main">Unión a la Academia</p>
                                                <p className="text-xs text-text-secondary mb-1">{selectedStudent.joinDate}</p>
                                                <p className="text-sm text-text-secondary">Inicio del viaje.</p>
                                            </div>
                                        </div>
                                  )}
                              </div>
                          </div>

                          {/* Study History */}
                          <div className="bg-white rounded-3xl p-8 border border-gray-100 shadow-card flex-1 flex flex-col">
                              <h3 className="font-bold text-lg text-text-main mb-6">Historial de Estudio</h3>
                              <div className="flex-1 overflow-y-auto max-h-[300px] pr-2 space-y-3">
                                  {completedVideos.map((video) => (
                                      <div key={video.id} className="flex items-start gap-3 p-3 bg-gray-50 rounded-xl">
                                          <div className="text-green-500 mt-0.5">
                                              <span className="material-symbols-outlined text-lg">check_circle</span>
                                          </div>
                                          <div>
                                              <p className="text-sm font-semibold text-text-main leading-tight">{video.title}</p>
                                              <p className="text-xs text-text-secondary mt-1">{video.category} • {video.level}</p>
                                          </div>
                                      </div>
                                  ))}
                                  {completedVideos.length === 0 && (
                                      <div className="text-center py-8 text-text-secondary">
                                          <span className="material-symbols-outlined text-3xl opacity-30 mb-2">video_library</span>
                                          <p className="text-sm">El alumno no ha marcado ningún video como completado aún.</p>
                                      </div>
                                  )}
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      );
  }

  // -------------------- GRID VIEW --------------------
  return (
    <div className="flex-1 overflow-y-auto p-4 md:p-8 lg:px-10 h-full">
      <ConfirmationModal 
        isOpen={confirmModal.isOpen}
        title={confirmModal.title}
        message={confirmModal.message}
        onConfirm={confirmModal.action}
        onCancel={() => setConfirmModal(prev => ({...prev, isOpen: false}))}
        type={confirmModal.type}
      />

      <div className="max-w-[1600px] mx-auto flex flex-col gap-8">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 pb-2">
          <div>
            <h2 className="text-text-main text-3xl font-bold tracking-tight mb-2">Gestión de Alumnos</h2>
            <p className="text-text-secondary font-medium">Monitorea el estatus financiero y progreso académico.</p>
          </div>
          <div className="flex gap-3">
              <button 
                onClick={handleExport}
                className="flex items-center gap-2 bg-white border border-gray-200 hover:bg-gray-50 text-text-main font-semibold py-3 px-5 rounded-full transition-all shadow-sm"
              >
                <span className="material-symbols-outlined text-[20px]">download</span>
                <span>Exportar CSV</span>
              </button>
              <button 
                onClick={handleCreate}
                className="flex items-center gap-2 bg-primary hover:bg-primary-hover text-white font-semibold py-3 px-6 rounded-full transition-all shadow-lg shadow-indigo-500/20 active:scale-95 transform"
              >
                <span className="material-symbols-outlined text-[20px]">person_add</span>
                <span>Nuevo Alumno</span>
              </button>
          </div>
        </div>

        {/* Toolbar */}
        <div className="bg-white rounded-2xl shadow-soft p-5 flex flex-col xl:flex-row gap-4 items-center border border-gray-100">
          <div className="relative w-full xl:flex-1 group">
            <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
              <span className="material-symbols-outlined text-text-secondary group-focus-within:text-primary transition-colors">search</span>
            </div>
            <input 
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="block w-full pl-11 pr-4 py-3.5 bg-gray-50 border-0 text-text-main placeholder-text-secondary rounded-xl focus:ring-2 focus:ring-primary/20 focus:bg-white transition-all text-sm font-medium" 
                placeholder="Buscar por nombre o ID..." 
                type="text"
            />
          </div>
          <div className="relative w-full md:w-40">
                <select 
                    value={filterStatus}
                    onChange={(e) => setFilterStatus(e.target.value)}
                    className="block w-full pl-4 pr-10 py-3.5 text-text-main bg-gray-50 border-0 focus:ring-2 focus:ring-primary/20 focus:bg-white sm:text-sm font-medium rounded-xl cursor-pointer appearance-none transition-all"
                >
                    <option value="all">Todos</option>
                    <option value="active">Al Día</option>
                    <option value="debtor">Deudores</option>
                    <option value="exam_ready">Examen Listo</option>
                </select>
            </div>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 pb-12">
          {filteredStudents.map((student) => (
            <div 
                key={student.id} 
                onClick={() => setSelectedStudentId(student.id)}
                className="group relative flex flex-col bg-white rounded-2xl p-6 transition-all duration-300 hover:shadow-xl hover:-translate-y-1 shadow-soft border border-gray-100 cursor-pointer"
            >
              <div className="flex justify-between items-start mb-5">
                <div className="h-16 w-16 rounded-2xl bg-cover bg-center shadow-md group-hover:scale-105 transition-transform duration-300" style={{ backgroundImage: `url("${student.avatarUrl}")` }}></div>
                <span className={`inline-flex items-center rounded-full px-3 py-1 text-[10px] font-bold ring-1 ring-inset tracking-wide ${getStatusColor(student.status)}`}>
                  {getStatusLabel(student.status)}
                </span>
              </div>
              <div className="mb-3">
                <h3 className="text-text-main font-bold text-lg truncate tracking-tight">{student.name}</h3>
                <p className="text-text-secondary text-sm font-medium">{student.rank} • {student.program}</p>
              </div>
              
              <div className="w-full bg-gray-100 rounded-full h-1.5 mb-4">
                  <div className="bg-primary h-1.5 rounded-full" style={{ width: `${Math.min(student.attendance, 100)}%` }}></div>
              </div>

              <div className="mt-auto pt-5 border-t border-gray-100 flex items-center justify-between text-text-secondary text-sm">
                <span className="bg-gray-50 px-2 py-1 rounded text-xs font-semibold text-gray-500">ID: #{student.id.slice(-4)}</span>
                <div className="flex gap-1">
                  <button onClick={(e) => handleEdit(student, e)} className="p-1.5 hover:bg-gray-100 rounded-lg text-text-secondary hover:text-primary transition-colors" title="Edit"><span className="material-symbols-outlined text-[20px]">edit</span></button>
                  <button onClick={(e) => handleDelete(student.id, e)} className="p-1.5 hover:bg-gray-100 rounded-lg text-text-secondary hover:text-red-500 transition-colors" title="Delete"><span className="material-symbols-outlined text-[20px]">delete</span></button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* CRUD Modal */}
      {showModal && (
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
              <div className="bg-white rounded-2xl p-8 w-full max-w-lg shadow-2xl animate-in fade-in zoom-in-95 duration-200">
                  <h2 className="text-2xl font-bold mb-6 text-text-main">{editingStudent ? 'Editar Alumno' : 'Nuevo Alumno'}</h2>
                  <form onSubmit={handleSubmit} className="flex flex-col gap-4">
                      <div className="grid grid-cols-2 gap-4">
                          <label className="block">
                              <span className="text-sm font-semibold text-text-main">Nombre</span>
                              <input required value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} className="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-primary focus:ring focus:ring-primary/20" />
                          </label>
                          <label className="block">
                              <span className="text-sm font-semibold text-text-main">Email</span>
                              <input required type="email" value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} className="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-primary focus:ring focus:ring-primary/20" />
                          </label>
                      </div>
                      <div className="grid grid-cols-2 gap-4">
                          <label className="block">
                              <span className="text-sm font-semibold text-text-main">Rango</span>
                              <select value={formData.rank} onChange={e => setFormData({...formData, rank: e.target.value})} className="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-primary focus:ring focus:ring-primary/20">
                                  <option>White Belt</option>
                                  <option>Blue Belt</option>
                                  <option>Purple Belt</option>
                                  <option>Brown Belt</option>
                                  <option>Black Belt</option>
                              </select>
                          </label>
                          <label className="block">
                              <span className="text-sm font-semibold text-text-main">Estado</span>
                              <select value={formData.status} onChange={e => setFormData({...formData, status: e.target.value as any})} className="mt-1 block w-full rounded-xl border-gray-300 shadow-sm focus:border-primary focus:ring focus:ring-primary/20">
                                  <option value="active">Activo</option>
                                  <option value="debtor">Deudor</option>
                                  <option value="exam_ready">Examen Listo</option>
                                  <option value="inactive">Inactivo</option>
                              </select>
                          </label>
                      </div>
                      <div className="flex gap-3 mt-6">
                          <button type="button" onClick={() => setShowModal(false)} className="flex-1 py-2.5 rounded-xl border border-gray-300 font-medium hover:bg-gray-50">Cancelar</button>
                          <button type="submit" className="flex-1 py-2.5 rounded-xl bg-primary text-white font-bold hover:bg-primary-hover shadow-lg shadow-primary/20">Guardar</button>
                      </div>
                  </form>
              </div>
          </div>
      )}
    </div>
  );
};

export default StudentsList;
